[
  {
    id: 1,
    Name: "Chetna Gogia",
    "Job Title": "Chief Human Resources Officer",
    "Linkedin URL": "http://www.linkedin.com/in/chetna-gogia",
    "Company Name": "GoKwik",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.gokwik.co/",
    "Company Linkedin": "http://www.linkedin.com/company/gokwik",
    "Company Social": "https://www.facebook.com/GoKwikCo/",
    "Company Twitter": "https://twitter.com/gokwik",
    Location: "Gurgaon, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 2,
    Name: "Iqbal Kaur",
    "Job Title": "Senior Manager - Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/iqbal-kaur-7bb65310",
    "Company Name": "Birdeye",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.birdeye.com/",
    "Company Linkedin": "http://www.linkedin.com/company/birdeye",
    "Company Social": "https://www.facebook.com/BirdeyeReviews",
    "Company Twitter": "https://twitter.com/birdeye_",
    Location: "Gurgaon, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 3,
    Name: "Vishwanadh Raju",
    "Job Title": "Head Talent Acquisition Operations- Talent Solutioning",
    "Linkedin URL": "http://www.linkedin.com/in/vishwanadh",
    "Company Name": "ANSR",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.ansr.com/",
    "Company Linkedin": "http://www.linkedin.com/company/ansr-consulting",
    "Company Social": "https://twitter.com/ansrglobal",
    "Company Twitter": "",
    Location: "Bengaluru, India",
    "Company Niche": "Management Consulting",
  },
  {
    id: 4,
    Name: "Rekha Singh",
    "Job Title": "Sr. Manager- Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/rekhaasingh",
    "Company Name": "Leena AI",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.leena.ai/",
    "Company Linkedin": "http://www.linkedin.com/company/l-e-e-n-a",
    "Company Social": "https://www.facebook.com/Leena-AI-301312863666839/",
    "Company Twitter": "",
    Location: "Delhi, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 5,
    Name: "Deepak Aggarwal",
    "Job Title": "Senior Executive Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/deepak-aggarwal-6393a31a",
    "Company Name": "Easyrewardz Software Services",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.easyrewardz.com/",
    "Company Linkedin": "http://www.linkedin.com/company/easyrewardz",
    "Company Social": "https://facebook.com/easyrewardzz/",
    "Company Twitter": "https://twitter.com/easyrewardz",
    Location: "New Delhi, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 6,
    Name: "Mamtha",
    "Job Title": "Director Talent Acquisition - Leadership Hiring",
    "Linkedin URL": "http://www.linkedin.com/in/mamtha-a-74436088",
    "Company Name": "Sigmoid",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.sigmoid.com/",
    "Company Linkedin": "http://www.linkedin.com/company/sigmoid-analytics",
    "Company Social":
      "http://www.facebook.com/pages/Sigmoid-Analytics/237480799741290",
    "Company Twitter": "http://twitter.com/sigmoidInc",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 7,
    Name: "Ravi Patel",
    "Job Title": "Senior Manager- Global Talent Hunter",
    "Linkedin URL": "http://www.linkedin.com/in/ravi-patel-3071b05",
    "Company Name": "Entropik",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.entropik.io/",
    "Company Linkedin": "http://www.linkedin.com/company/entropiktech",
    "Company Social": "http://facebook.com/entropiktech",
    "Company Twitter": "http://twitter.com/entropiktech",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 8,
    Name: "Naveen Mon",
    "Job Title": "Recruitment Manager",
    "Linkedin URL": "http://www.linkedin.com/in/naveenrecruiter",
    "Company Name": "ANSR",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.ansr.com/",
    "Company Linkedin": "http://www.linkedin.com/company/ansr-consulting",
    "Company Social": "https://twitter.com/ansrglobal",
    "Company Twitter": "",
    Location: "Karnataka, India",
    "Company Niche": "Management Consulting",
  },
  {
    id: 9,
    Name: "Omkar Pradhan",
    "Job Title": "Associate Director - People,Culture & Talent",
    "Linkedin URL": "http://www.linkedin.com/in/omkarpradhan7",
    "Company Name": "GoKwik",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.gokwik.co/",
    "Company Linkedin": "http://www.linkedin.com/company/gokwik",
    "Company Social": "https://www.facebook.com/GoKwikCo/",
    "Company Twitter": "https://twitter.com/gokwik",
    Location: "Gurugram, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 10,
    Name: "Raj Raghavan",
    "Job Title": "",
    "Linkedin URL": "http://www.linkedin.com/in/raj-raghavan-4285251",
    "Company Name": "CoreStack",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.corestack.io/",
    "Company Linkedin": "http://www.linkedin.com/company/corestack",
    "Company Social": "https://www.facebook.com/corestack",
    "Company Twitter": "https://twitter.com/corestack",
    Location: "Gurugram, India",
    "Company Niche": "Information Technology & Services",
  },

  {
    id: 11,
    Name: "Omkar Pradhan",
    "Job Title": "Associate Director - People,Culture & Talent",
    "Linkedin URL": "http://www.linkedin.com/in/omkarpradhan7",
    "Company Name": "GoKwik",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.gokwik.co/",
    "Company Linkedin": "http://www.linkedin.com/company/gokwik",
    "Company Social": "https://www.facebook.com/GoKwikCo/",
    "Company Twitter": "https://twitter.com/gokwik",
    Location: "Gurugram, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 12,
    Name: "Raj Raghavan",
    "Job Title": "",
    "Linkedin URL": "http://www.linkedin.com/in/raj-raghavan-4285251",
    "Company Name": "CoreStack",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.corestack.io/",
    "Company Linkedin": "http://www.linkedin.com/company/corestack",
    "Company Social": "https://www.facebook.com/corestack",
    "Company Twitter": "https://twitter.com/corestack",
    Location: "Gurugram, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 13,
    Name: "Naga Siddharth",
    "Job Title": "Chief Human Resources Officer",
    "Linkedin URL": "http://www.linkedin.com/in/nagasiddharth",
    "Company Name": "UrbanPiper",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.urbanpiper.com/",
    "Company Linkedin": "http://www.linkedin.com/company/urbanpiper",
    "Company Social": "https://www.facebook.com/urbanpiper/",
    "Company Twitter": "https://twitter.com/urbanpiper",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 14,
    Name: "Anjali Sharma",
    "Job Title": "Talent Acquisition Executive II",
    "Linkedin URL": "http://www.linkedin.com/in/oeanjali",
    "Company Name": "Junglee Games",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.jungleegames.com/",
    "Company Linkedin": "http://www.linkedin.com/company/junglee-games",
    "Company Social": "",
    "Company Twitter": "",
    Location: "Noida, India",
    "Company Niche": "Computer Games",
  },
  {
    id: 15,
    Name: "Indu Balakrishnan",
    "Job Title": "Technical Recruiter",
    "Linkedin URL": "http://www.linkedin.com/in/indu-balakrishnan-4105a35",
    "Company Name": "Tenstorrent Inc.",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.tenstorrent.com/",
    "Company Linkedin": "http://www.linkedin.com/company/tenstorrent-inc.",
    "Company Social": "https://twitter.com/tenstorrent",
    "Company Twitter": "",
    Location: "Bengaluru, India",
    "Company Niche": "Computer Hardware",
  },
  {
    id: 16,
    Name: "Priyanka Mishra",
    "Job Title": "Sr. Manager - Culture & Talent",
    "Linkedin URL": "http://www.linkedin.com/in/priyankamishra14",
    "Company Name": "Headout",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.headout.com/",
    "Company Linkedin": "http://www.linkedin.com/company/headout-com",
    "Company Social": "https://www.facebook.com/headoutapp",
    "Company Twitter": "https://twitter.com/Headout_App",
    Location: "Karnataka, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 17,
    Name: "Nishant Das",
    "Job Title": "VP & Head of Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/nishantd",
    "Company Name": "CoinSwitch",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.coinswitch.co/",
    "Company Linkedin": "http://www.linkedin.com/company/coinswitch",
    "Company Social": "https://facebook.com/coinswitch",
    "Company Twitter": "https://twitter.com/coinswitch",
    Location: "Mumbai, India",
    "Company Niche": "Financial Services",
  },
  {
    id: 18,
    Name: "Blesson Cherian",
    "Job Title": "Recruiting Lead",
    "Linkedin URL": "http://www.linkedin.com/in/blessoncherian",
    "Company Name": "Spotnana",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.spotnana.com/",
    "Company Linkedin": "http://www.linkedin.com/company/spotnanatechnology",
    "Company Social": "https://facebook.com/spotnana",
    "Company Twitter": "https://twitter.com/spotnana",
    Location: "India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 19,
    Name: "Harish Sharma",
    "Job Title": "SR IT Recruiter",
    "Linkedin URL": "http://www.linkedin.com/in/harish-sharma-10606246",
    "Company Name": "MX Player",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.mxplayer.in/",
    "Company Linkedin": "http://www.linkedin.com/company/mx-player",
    "Company Social": "https://www.facebook.com/MXPlayer",
    "Company Twitter": "https://twitter.com/mxplayer",
    Location: "Mumbai, India",
    "Company Niche": "Entertainment",
  },
  {
    id: 20,
    Name: "Shamsher",
    "Job Title":
      "Assistant Manager Talent Acquisition at FarMart Services Pvt Ltd",
    "Linkedin URL": "http://www.linkedin.com/in/sham-sher",
    "Company Name": "FarMart",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.farmart.co/",
    "Company Linkedin": "http://www.linkedin.com/company/farmart-app-os",
    "Company Social":
      "https://www.facebook.com/FarMart-AgriTech-2059869087580734/",
    "Company Twitter": "https://twitter.com/farMart_",
    Location: "Delhi, India",
    "Company Niche": "Farming",
  },
  {
    id: 21,
    Name: "Jayashree Vasudevan",
    "Job Title": "Senior Talent Acquisition Specialist",
    "Linkedin URL": "http://www.linkedin.com/in/jayashree-vasudevan",
    "Company Name": "Avataar",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.avataar.ai/",
    "Company Linkedin": "http://www.linkedin.com/company/avataar-",
    "Company Social": "https://www.facebook.com/Avataar.me",
    "Company Twitter": "https://twitter.com/Avataar",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 22,
    Name: "Ankur Chaudhary",
    "Job Title": "",
    "Linkedin URL": "http://www.linkedin.com/in/ankur-chaudhary-91844991",
    "Company Name": "JUSPAY",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.juspay.in/",
    "Company Linkedin": "http://www.linkedin.com/company/juspay-technologies",
    "Company Social": "http://facebook.com/juspay.in",
    "Company Twitter": "http://twitter.com/juspay",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 23,
    Name: "Nimish Jain",
    "Job Title": "Talent Acquisition Lead",
    "Linkedin URL": "http://www.linkedin.com/in/nimishj",
    "Company Name": "Wishup.co",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.wishup.co/",
    "Company Linkedin": "http://www.linkedin.com/company/wishup-services",
    "Company Social": "http://www.facebook.com/wishupnow",
    "Company Twitter": "https://twitter.com/wishupnow",
    Location: "India",
    "Company Niche": "Management Consulting",
  },
  {
    id: 24,
    Name: "Chaithrashree Chandrashekar",
    "Job Title": "Manager, Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/chaithrashreechandrashekar",
    "Company Name": "PlanSource",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.plansource.com/",
    "Company Linkedin": "http://www.linkedin.com/company/plansource",
    "Company Social": "http://www.facebook.com/plansourceHRHQ",
    "Company Twitter": "http://www.twitter.com/PlanSource",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 25,
    Name: "Dharmendra Rawat",
    "Job Title": "Head of Talent Acquisition",
    "Linkedin URL":
      "http://www.linkedin.com/in/dharmendra-singh-rawat-aab49916",
    "Company Name": "LUMIQ",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.lumiq.ai/",
    "Company Linkedin": "http://www.linkedin.com/company/lumiqai",
    "Company Social": "https://www.facebook.com/Lumiq-103640211223948/",
    "Company Twitter": "https://twitter.com/lumiq_ai",
    Location: "India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 26,
    Name: "Sanjo Joshi",
    "Job Title": "Senior Talent Resourcer - People & Culture",
    "Linkedin URL": "http://www.linkedin.com/in/sanjojoshi",
    "Company Name": "Bayzat",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.bayzat.com/",
    "Company Linkedin": "http://www.linkedin.com/company/bayzat",
    "Company Social": "http://facebook.com/bayzatme",
    "Company Twitter": "http://twitter.com/bayzatme",
    Location: "India",
    "Company Niche": "Human Resources",
  },
  {
    id: 27,
    Name: "Rajesh Charan",
    "Job Title": "Assistant Manager HR - Talent Life Cycle",
    "Linkedin URL": "http://www.linkedin.com/in/rajeshsinghcharan",
    "Company Name": "NAV Backoffice",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.navbackoffice.com/",
    "Company Linkedin": "http://www.linkedin.com/company/nav-backoffice",
    "Company Social": "",
    "Company Twitter": "",
    Location: "Jaipur, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 28,
    Name: "Nirvesh Mehrotra",
    "Job Title": "Recruitment Head",
    "Linkedin URL": "http://www.linkedin.com/in/nirvesh-mehrotra-822a5b55",
    "Company Name": "GoKwik",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.gokwik.co/",
    "Company Linkedin": "http://www.linkedin.com/company/gokwik",
    "Company Social": "https://www.facebook.com/GoKwikCo/",
    "Company Twitter": "https://twitter.com/gokwik",
    Location: "Gurgaon, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 29,
    Name: "Vikas Kumar",
    "Job Title": "Sr. Talent Acquisition Executive",
    "Linkedin URL": "http://www.linkedin.com/in/vikaskumar96",
    "Company Name": "fleetx.io",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.fleetx.io/",
    "Company Linkedin": "http://www.linkedin.com/company/fleetx-io",
    "Company Social": "https://www.facebook.com/fleetx.io",
    "Company Twitter": "https://twitter.com/fleetx_io",
    Location: "Gurugram, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 30,
    Name: "Shhweta Joshi",
    "Job Title": "Head : Talent Acquisition & Employer Branding",
    "Linkedin URL": "http://www.linkedin.com/in/shwetajoshihrd",
    "Company Name": "CashKaro.com",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.cashkaro.com/",
    "Company Linkedin": "http://www.linkedin.com/company/cashkaro-com",
    "Company Social": "https://facebook.com/cashkaro",
    "Company Twitter": "https://twitter.com/Cashkarocom",
    Location: "Gurgaon, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 31,
    Name: "Dimpy Mehra",
    "Job Title": "Head - Talent Acquisition & Management",
    "Linkedin URL": "http://www.linkedin.com/in/mehradimpy",
    "Company Name": "Kutumb",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.kutumbapp.com/",
    "Company Linkedin": "http://www.linkedin.com/company/kutumbapp",
    "Company Social": "https://facebook.com/kutumbapp",
    "Company Twitter": "https://twitter.com/kutumbapp",
    Location: "Bengaluru, India",
    "Company Niche": "Online Media",
  },
  {
    id: 32,
    Name: "Shilpa Kamble",
    "Job Title": "Sr. Talent Acquisition Specialist",
    "Linkedin URL": "http://www.linkedin.com/in/shilpa-kamble-652373142",
    "Company Name": "Seclore",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.seclore.com/",
    "Company Linkedin": "http://www.linkedin.com/company/seclore",
    "Company Social": "https://facebook.com/seclore",
    "Company Twitter": "https://twitter.com/secloretech",
    Location: "Pune, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 33,
    Name: "Monika Kaushik",
    "Job Title": "Assistant Manager-Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/monika-kaushik-1802793a",
    "Company Name": "Builder.ai",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.builder.ai/",
    "Company Linkedin": "http://www.linkedin.com/company/builderai",
    "Company Social": "https://www.facebook.com/builderai/",
    "Company Twitter": "https://twitter.com/builderAI",
    Location: "Gurgaon, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 34,
    Name: "Dharmik Gohel",
    "Job Title": "Director - Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/dharmik-gohel-a1017a8b",
    "Company Name": "Atlan",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.atlan.com/",
    "Company Linkedin": "http://www.linkedin.com/company/atlan-hq",
    "Company Social": "https://www.facebook.com/SocialCops",
    "Company Twitter": "https://twitter.com/Social_Cops",
    Location: "Delhi, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 35,
    Name: "Deepa Rani",
    "Job Title": "Lead - Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/deep-r",
    "Company Name": "Awign",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.awign.com/",
    "Company Linkedin": "http://www.linkedin.com/company/awign-enterprises",
    "Company Social": "https://www.facebook.com/awign.internships",
    "Company Twitter": "https://twitter.com/in_awign",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 36,
    Name: "Shweta",
    "Job Title": "Talent Acquisition Specialist",
    "Linkedin URL": "http://www.linkedin.com/in/vyasshweta",
    "Company Name": "Ula",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.ula.app/",
    "Company Linkedin": "http://www.linkedin.com/company/uladotapp",
    "Company Social": "https://facebook.com/uladotapp/",
    "Company Twitter": "https://twitter.com/uladotapp",
    Location: "Bengaluru, India",
    "Company Niche": "",
  },
  {
    id: 37,
    Name: "Sumanth Krishna",
    "Job Title":
      "Talent Advocate - Architecting International Tech Teams🚀 | Branding💥 - APAC | India | EMEA | USA",
    "Linkedin URL": "http://www.linkedin.com/in/sumanth-krishna",
    "Company Name": "LambdaTest",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.lambdatest.com/",
    "Company Linkedin": "http://www.linkedin.com/company/lambdatest",
    "Company Social": "https://www.facebook.com/lambdatest/",
    "Company Twitter": "https://twitter.com/Lambdatesting",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 38,
    Name: "Keerthana S",
    "Job Title": "Talent Acquisition Lead",
    "Linkedin URL": "http://www.linkedin.com/in/keerthana-s-589704a8",
    "Company Name": "Experience.com",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.experience.com/",
    "Company Linkedin": "http://www.linkedin.com/company/experiencecom",
    "Company Social": "https://www.facebook.com/experiencecom",
    "Company Twitter": "http://www.twitter.com/socialsurveyme",
    Location: "Chennai, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 39,
    Name: "Saine Ghosal",
    "Job Title": "Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/saine-ghosal-58280320",
    "Company Name": "Locus",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.locus.sh/",
    "Company Linkedin": "http://www.linkedin.com/company/locus-sh",
    "Company Social": "http://www.facebook.com/epilocus?sk=info",
    "Company Twitter": "https://twitter.com/epilocus",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 40,
    Name: "Ajeet Kumar",
    "Job Title": "Assistant Manager Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/ajeetkumar309",
    "Company Name": "DotPe",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.dotpe.in/",
    "Company Linkedin": "http://www.linkedin.com/company/dotpein",
    "Company Social": "",
    "Company Twitter": "",
    Location: "Gurgaon, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 41,
    Name: "Gunjan Agarwal",
    "Job Title": "All things Talent",
    "Linkedin URL": "http://www.linkedin.com/in/gunjanagarwal25",
    "Company Name": "HyperVerge",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.hyperverge.co/",
    "Company Linkedin": "http://www.linkedin.com/company/hyperverge-inc-",
    "Company Social": "https://www.facebook.com/pg/HyperVerge/",
    "Company Twitter": "https://twitter.com/HyperVerge",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 42,
    Name: "Kiran Kumar",
    "Job Title": "Office of the CTO - Talent Acquisition",
    "Linkedin URL": "http://www.linkedin.com/in/mkk0315",
    "Company Name": "Narvar",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.narvar.com/",
    "Company Linkedin": "http://www.linkedin.com/company/narvar",
    "Company Social": "https://www.facebook.com/NarvarInc/",
    "Company Twitter": "https://twitter.com/narvarinc",
    Location: "Hyderabad, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 43,
    Name: "Gagan Sharma",
    "Job Title": "Chief Human Resource Officer",
    "Linkedin URL": "http://www.linkedin.com/in/gagan-sharma-26b69121",
    "Company Name": "Namdev Finvest Private Limited",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.namfin.in/",
    "Company Linkedin":
      "http://www.linkedin.com/company/namdev-finvest-private-limited",
    "Company Social": "",
    "Company Twitter": "",
    Location: "New Delhi, India",
    "Company Niche": "Financial Services",
  },
  {
    id: 44,
    Name: "Himanshu Jain",
    "Job Title": "Talent Acquisition Lead",
    "Linkedin URL": "http://www.linkedin.com/in/himanshu-jain-24666115",
    "Company Name": "Privacera",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.privacera.com/",
    "Company Linkedin": "http://www.linkedin.com/company/privacera",
    "Company Social": "",
    "Company Twitter": "",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 45,
    Name: "Shraddha Jain",
    "Job Title": "Sr. Talent Acquisition Consultant",
    "Linkedin URL": "http://www.linkedin.com/in/shraddha-jain-82a1a216",
    "Company Name": "Uniphore",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.uniphore.com/",
    "Company Linkedin": "http://www.linkedin.com/company/uniphore",
    "Company Social": "https://www.facebook.com/uniphore/",
    "Company Twitter": "https://twitter.com/uniphore",
    Location: "Gurgaon, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 46,
    Name: "Priyanka Kumar",
    "Job Title": "Senior Talent Acquisition Consultant",
    "Linkedin URL": "http://www.linkedin.com/in/priyanka-kumar-b6a00612",
    "Company Name": "Uniphore",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.uniphore.com/",
    "Company Linkedin": "http://www.linkedin.com/company/uniphore",
    "Company Social": "",
    "Company Twitter": "",
    Location: "Gurgaon, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 47,
    Name: "Sanjay Mohapatra",
    "Job Title": "Talent Acquisition Specialist",
    "Linkedin URL": "http://www.linkedin.com/in/sanjay-mohapatra-b77054a4",
    "Company Name": "Mobivite",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.mobivite.com/",
    "Company Linkedin": "http://www.linkedin.com/company/mobivite",
    "Company Social": "",
    "Company Twitter": "",
    Location: "Bengaluru, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 48,
    Name: "Sandeep Hegde",
    "Job Title": "Talent Acquisition Specialist",
    "Linkedin URL": "http://www.linkedin.com/in/sandeep-hegde",
    "Company Name": "Ganit",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.ganit.com/",
    "Company Linkedin": "http://www.linkedin.com/company/ganit",
    "Company Social": "",
    "Company Twitter": "",
    Location: "Mumbai, India",
    "Company Niche": "Information Technology & Services",
  },
  {
    id: 49,
    Name: "Vikram Wadhawan",
    "Job Title": "Chief People Officer",
    "Linkedin URL": "http://www.linkedin.com/in/vikram-wadhawan-b1b02b12",
    "Company Name": "Himadri Speciality Chemical Limited",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.himadri.com/",
    "Company Linkedin":
      "http://www.linkedin.com/company/himadri-speciality-chemical-limited",
    "Company Social": "",
    "Company Twitter": "",
    Location: "Kolkata, India",
    "Company Niche": "Chemicals",
  },
  {
    id: 50,
    Name: "Ramesh Kumar",
    "Job Title": "Senior Talent Acquisition Specialist",
    "Linkedin URL": "http://www.linkedin.com/in/ramesh-kumar-5b49b625",
    "Company Name": "Wadhawan Group",
    Status: "",
    "Applied for Internship/Job": "",
    "Company Website": "http://www.wadhawangroup.com/",
    "Company Linkedin": "http://www.linkedin.com/company/wadhawan-group",
    "Company Social": "",
    "Company Twitter": "",
    Location: "Mumbai, India",
    "Company Niche": "Consumer Services",
  },

  {
    id: 51,
    name: "Tanvi Saxena",
    title: "Senior Manager - Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/tanvisaxena87",
    company: "Builder.ai",
    website: "http://www.builder.ai/",
    company_linkedin: "http://www.linkedin.com/company/builderai",
    facebook: "https://www.facebook.com/builderai/",
    twitter: "https://twitter.com/builderAI",
    location: "Gurugram, India",
    industry: "Information Technology & Services",
  },
  {
    id: 52,
    name: "Shashank Shekher",
    title: "Head Of Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/sshekher",
    company: "Replicon",
    website: "http://www.replicon.com/",
    company_linkedin: "http://www.linkedin.com/company/replicon",
    facebook: "http://www.facebook.com/Replicon.inc",
    twitter: "http://www.twitter.com/replicon",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 53,
    name: "Akshita Kochar",
    title: "Sr. Talent Magnet",
    linkedin: "http://www.linkedin.com/in/akshitakochar",
    company: "Keka HR",
    website: "http://www.keka.com/",
    company_linkedin: "http://www.linkedin.com/company/keka-hr",
    facebook: "https://facebook.com/kekadotcom/",
    twitter: "https://twitter.com/KekaDotCom",
    location: "Hyderabad, India",
    industry: "Human Resources",
  },
  {
    id: 54,
    name: "Rahul Jana",
    title: "Senior Talent Acquisition Lead",
    linkedin: "http://www.linkedin.com/in/rahul-jana-7a784b85",
    company: "Contentstack",
    website: "http://www.contentstack.com/",
    company_linkedin: "http://www.linkedin.com/company/contentstack",
    facebook: "https://www.facebook.com/contentstack",
    twitter: "https://twitter.com/contentstack",
    location: "Mumbai, India",
    industry: "Information Technology & Services",
  },
  {
    id: 55,
    name: "Ashish Kumar",
    title: "Senior Associate Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/ashish-kumar-974b90a0",
    company: "FITTR",
    website: "http://www.fittr.com/",
    company_linkedin: "http://www.linkedin.com/company/fittr",
    facebook: "https://facebook.com/Fittrwithsquats",
    twitter: "https://twitter.com/FITTRwithsquats",
    location: "Bengaluru, India",
    industry: "Health, Wellness & Fitness",
  },
  {
    id: 56,
    name: "Vini",
    title: "Manager - HR Talent Management",
    linkedin: "http://www.linkedin.com/in/vinithomashr",
    company: "Zafin",
    website: "http://www.zafin.com/",
    company_linkedin: "http://www.linkedin.com/company/zafin",
    facebook: "https://www.facebook.com/Zafin.Inc/",
    twitter: "https://twitter.com/zafin",
    location: "Thiruvananthapuram, India",
    industry: "Information Technology & Services",
  },
  {
    id: 57,
    name: "Piyali Bhattacharya",
    title: "Talent Acquisition Lead",
    linkedin: "http://www.linkedin.com/in/piyali-bhattacharya-a1421796",
    company: "Anchanto",
    website: "http://www.anchanto.com/",
    company_linkedin: "http://www.linkedin.com/company/anchanto",
    facebook: "https://www.facebook.com/anchanto/",
    twitter: "https://twitter.com/anchantodotcom",
    location: "Pune, India",
    industry: "Information Technology & Services",
  },
  {
    id: 58,
    name: "Amrith Sk",
    title: "Deputy Manager Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/amrith-sk-330410116",
    company: "CollegeDekho",
    website: "http://www.collegedekho.com/",
    company_linkedin: "http://www.linkedin.com/company/collegedekho",
    facebook: "https://facebook.com/CollegeDekho",
    twitter: "https://twitter.com/collegedekho",
    location: "Bengaluru, India",
    industry: "Government Administration",
  },
  {
    id: 59,
    name: "Vikram Bhardwaj",
    title: "Director, Global Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/vikram-bhardwaj-95ab4913",
    company: "Yellow.ai",
    website: "http://www.yellow.ai/",
    company_linkedin: "http://www.linkedin.com/company/yellowdotai",
    facebook: "https://www.facebook.com/YellowMssngr",
    twitter: "https://twitter.com/yellowmssngr",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 60,
    name: "Anusha Reddy",
    title: "Talent Acquisition Specialist",
    linkedin: "http://www.linkedin.com/in/anusha-reddy-372111146",
    company: "Increff",
    website: "http://www.increff.com/",
    company_linkedin: "http://www.linkedin.com/company/increff",
    facebook:
      "https://www.facebook.com/pages/category/Software-Company/Increff-317897195823739/",
    twitter: "https://twitter.com/increff",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 61,
    name: "Nitesh Singh",
    title: "Senior Manager Talent Acquisition-Leadership hiring",
    linkedin: "http://www.linkedin.com/in/nitesh-singh7",
    company: "Yubi",
    website: "http://www.go-yubi.com/",
    company_linkedin: "http://www.linkedin.com/company/go-yubi",
    twitter: "https://twitter.com/Yubi_fin",
    location: "Bengaluru, India",
    industry: "Financial Services",
  },
  {
    id: 62,
    name: "Narahari Pc",
    title: "Manager - Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/naraharipc",
    company: "Replicon",
    website: "http://www.replicon.com/",
    company_linkedin: "http://www.linkedin.com/company/replicon",
    facebook: "http://www.facebook.com/Replicon.inc",
    twitter: "http://www.twitter.com/replicon",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 63,
    name: "Vikram Singh",
    title: "Manager - Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/vikramlimat1",
    company: "apna",
    website: "http://www.apna.co/",
    company_linkedin: "http://www.linkedin.com/company/apnahq",
    facebook: "https://www.facebook.com/APNA-2386268451700180",
    twitter: "https://twitter.com/apnahq",
    location: "Gurugram, India",
    industry: "Information Technology & Services",
  },
  {
    id: 64,
    name: "Piyush Raghuvanshi",
    title: "Head - Talent & Growth",
    linkedin: "http://www.linkedin.com/in/piyushraghuvanshi",
    company: "apna",
    website: "http://www.apna.co/",
    company_linkedin: "http://www.linkedin.com/company/apnahq",
    facebook: "https://www.facebook.com/APNA-2386268451700180",
    twitter: "https://twitter.com/apnahq",
    location: "Gurugram, India",
    industry: "Information Technology & Services",
  },
  {
    id: 65,
    name: "Sapna Pathak",
    title: "Vice President HR and Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/sapna-pathak-she-her-a398607",
    company: "Cogoport",
    website: "http://www.cogoport.com/",
    company_linkedin: "http://www.linkedin.com/company/cogoport",
    facebook: "https://www.facebook.com/cogoport",
    twitter: "https://twitter.com/Cogoport",
    location: "Bengaluru, India",
    industry: "Logistics & Supply Chain",
  },
  {
    id: 66,
    name: "Pranav Kumar",
    title: "Sr. Talent Acquisition Specialist",
    linkedin: "http://www.linkedin.com/in/pranav-kumar-8251528b",
    company: "Bluejeans by Verizon",
    website: "http://www.bluejeans.com/",
    company_linkedin: "http://www.linkedin.com/company/bluejeans-network",
    facebook: "https://www.facebook.com/bluejeansnetwork",
    twitter: "https://twitter.com/bluejeansnet",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 67,
    name: "Karan Bhatia",
    title: "Head Of Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/karan-bhatia-80a2818",
    company: "IQVIA",
    website: "http://www.iqvia.com/",
    company_linkedin: "http://www.linkedin.com/company/iqvia",
    facebook: "https://www.facebook.com/IQVIA/",
    twitter: "https://twitter.com/IQVIA",
    location: "Gurugram, India",
    industry: "Information Technology & Services",
  },
  {
    id: 68,
    name: "Deepti Upadhyaya",
    title: "HR Business Partner",
    linkedin: "http://www.linkedin.com/in/deepti-upadhyaya",
    company: "apna",
    website: "http://www.apna.co/",
    company_linkedin: "http://www.linkedin.com/company/apnahq",
    facebook: "https://www.facebook.com/APNA-2386268451700180",
    twitter: "https://twitter.com/apnahq",
    location: "Gurugram, India",
    industry: "Information Technology & Services",
  },
  {
    id: 69,
    name: "Nikhil Dhingra",
    title: "Head of Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/nikhil-dhingra-2b128615",
    company: "Freelancer",
    website: "http://www.freelancer.com/",
    company_linkedin: "http://www.linkedin.com/company/freelancer",
    facebook: "https://www.facebook.com/Freelancercom/",
    twitter: "https://twitter.com/Freelancer",
    location: "New Delhi, India",
    industry: "Internet",
  },
  {
    id: 70,
    name: "Prashant D",
    title: "Talent Acquisition Specialist",
    linkedin: "http://www.linkedin.com/in/prashant-d-261b86159",
    company: "Blue Planet",
    website: "http://www.blueplanet.com/",
    company_linkedin: "http://www.linkedin.com/company/blueplanet",
    facebook: "https://www.facebook.com/blueplanet/",
    twitter: "https://twitter.com/blueplanet",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 71,
    name: "Dishaa Ranjan",
    title: "Building Talent & Culture",
    linkedin: "http://www.linkedin.com/in/dishaaranjan",
    company: "Novo",
    website: "http://www.novo.co/",
    company_linkedin: "http://www.linkedin.com/company/novo-hq",
    facebook: "https://www.facebook.com/novobank/",
    twitter: "https://twitter.com/banknovo",
    location: "Gurgaon, India",
    industry: "Financial Services",
  },
  {
    id: 72,
    name: "Tushar Vats",
    title: "Assistant Manager - Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/tushar-vats-a3bb0493",
    company: "Honasa Consumer Pvt Ltd (Mamaearth)",
    website: "http://www.honasa.in/",
    company_linkedin: "http://www.linkedin.com/company/honasa-consumer-ltd",
    location: "Gurgaon, India",
    industry: "Mechanical Or Industrial Engineering",
  },
  {
    id: 73,
    name: "Mohammad Kashif",
    title: "Head Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/mohammad-kashif-5287a98",
    company: "Believe Pte Ltd",
    website: "http://www.believe.sg/",
    company_linkedin: "http://www.linkedin.com/company/believesingapore",
    location: "Delhi, India",
    industry: "Mechanical Or Industrial Engineering",
  },
  {
    id: 74,
    name: "Shobha Nanj",
    title: "Talent Acquisition Manager",
    linkedin: "http://www.linkedin.com/in/shobhananj",
    company: "Toddle - Your Teaching Partner",
    website: "http://www.toddleapp.com/",
    company_linkedin: "http://www.linkedin.com/company/toddle",
    facebook: "https://facebook.com/toddle.edu/",
    twitter: "https://twitter.com/toddle_edu",
    location: "Bengaluru, India",
    industry: "Government Administration",
  },
  {
    id: 75,
    name: "Keerthi Priya",
    title: "Talent Acquisition Specialist",
    linkedin: "http://www.linkedin.com/in/keerthi-priya-goud",
    company: "RED.Health (Formerly StanPlus)",
    website: "http://www.red.health/",
    company_linkedin: "http://www.linkedin.com/company/stanplus-redhealth",
    facebook: "https://www.facebook.com/stanplustech/",
    twitter: "https://twitter.com/theredhealth",
    location: "Hyderabad, India",
    industry: "Hospital & Health Care",
  },
  {
    id: 76,
    name: "Vibhor Kumar",
    title: "Talent Partner",
    linkedin: "http://www.linkedin.com/in/vibhorkumar",
    company: "smallcase",
    website: "http://www.smallcase.com/",
    company_linkedin: "http://www.linkedin.com/company/smallcase",
    facebook: "https://facebook.com/smallcaseHQ",
    twitter: "http://twitter.com/smallcaseHQ",
    location: "Delhi, India",
    industry: "Financial Services",
  },
  {
    id: 77,
    name: "Pavan Suman",
    title: "Assistant People Manager-IT Recruitment",
    linkedin: "http://www.linkedin.com/in/pavan-kumar-suman-0540ab24",
    company: "Clovia",
    website: "http://www.clovia.com/",
    company_linkedin: "http://www.linkedin.com/company/clovia-lingerie",
    facebook: "https://www.facebook.com/cloviafashions",
    twitter: "https://twitter.com/Cloviafashions",
    location: "Noida, India",
    industry: "Retail",
  },
  {
    id: 78,
    name: "Sushma Mondal",
    title: "Senior Talent Success Executive",
    linkedin: "http://www.linkedin.com/in/sushma-mondal-519080161",
    company: "Skuad",
    website: "http://www.skuad.io/",
    company_linkedin: "http://www.linkedin.com/company/joinskuad",
    facebook: "https://www.facebook.com/joinskuad.io/",
    twitter: "https://twitter.com/joinskuad",
    location: "Noida, India",
    industry: "Information Technology & Services",
  },
  {
    id: 79,
    name: "Megha Srivastava",
    title: "APAC & EMEA - Talent Acquisition and HRBP",
    linkedin: "http://www.linkedin.com/in/meghasrivastava",
    company: "Jeeves",
    website: "http://www.tryjeeves.com/",
    company_linkedin: "http://www.linkedin.com/company/tryjeeves",
    facebook: "https://www.facebook.com/tryjeeves",
    twitter: "https://twitter.com/jeeves_inc",
    location: "Bengaluru, India",
    industry: "Financial Services",
  },
  {
    id: 80,
    name: "Sai M",
    title: "Talent Acquisition Lead",
    linkedin: "http://www.linkedin.com/in/sai-charan-m-he-him-5a15434a",
    company: "DataWeave",
    website: "http://www.dataweave.com/",
    company_linkedin: "http://www.linkedin.com/company/dataweave",
    facebook: "https://www.facebook.com/DataWeave/",
    twitter: "https://twitter.com/dataweavein",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 81,
    name: "Anand Khot",
    title: "Chief Human Resources Officer",
    linkedin: "http://www.linkedin.com/in/anand-khot-hrcatalyst",
    company: "Pharmarack",
    website: "http://www.pharmarack.com/",
    company_linkedin: "http://www.linkedin.com/company/pharmaracktech",
    facebook: "https://facebook.com/pharmaracktech/",
    twitter: "https://twitter.com/pharmaracktech",
    location: "Pune, India",
    industry: "Information Technology & Services",
  },
  {
    id: 82,
    name: "Harish Kumar",
    title: "Sr. Recruiter Preferred Clients - Randstad Life Sciences",
    linkedin: "http://www.linkedin.com/in/harish-kumar-177126a4",
    company: "Randstad Offshore Services",
    website: "http://www.randstadoffshore.com/",
    company_linkedin:
      "http://www.linkedin.com/company/randstad-offshore-services",
    facebook: "https://www.facebook.com/RandstadOffshoreServices",
    location: "Hyderabad, India",
    industry: "Human Resources",
  },
  {
    id: 83,
    name: "Sivakumar Kadirvelu",
    title: "Recruiting Manager",
    linkedin: "http://www.linkedin.com/in/shivask",
    company: "Moveworks",
    website: "http://www.moveworks.com/",
    company_linkedin: "http://www.linkedin.com/company/moveworksai",
    facebook: "https://facebook.com/moveworksAI/",
    twitter: "https://twitter.com/moveworks",
    location: "Karnataka, India",
    industry: "Information Technology & Services",
  },
  {
    id: 84,
    name: "Jaspreet Singh",
    title: "Director Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/jsingh-ta",
    company: "Multiplier",
    website: "http://www.multiplier.org/",
    company_linkedin: "http://www.linkedin.com/company/usemultiplier",
    location: "Bengaluru, India",
    industry: "Internet",
  },
  {
    id: 85,
    name: "Rajat Walia",
    title: "Senior IT Recruiter",
    linkedin: "http://www.linkedin.com/in/rajat-walia-12b484120",
    company: "KlearNow.AI",
    website: "http://www.klearnow.ai/",
    company_linkedin: "http://www.linkedin.com/company/klearnow-corp",
    twitter: "https://twitter.com/klearnow",
    location: "Gurgaon, India",
    industry: "Information Technology & Services",
  },
  {
    id: 86,
    name: "Niket Iyer",
    title: "Lead Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/niket-iyer",
    company: "PLATINUM EXPLORE",
    website: "http://www.platinumexplore.com/",
    company_linkedin: "http://www.linkedin.com/company/platinum-explore",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 87,
    name: "Abhinav Soni",
    title: "Talent Acquisition Specialist",
    linkedin: "http://www.linkedin.com/in/abhinavsoni",
    company: "Unisys",
    website: "http://www.unisys.com/",
    company_linkedin: "http://www.linkedin.com/company/unisys",
    location: "Noida, India",
    industry: "Information Technology & Services",
  },
  {
    id: 88,
    name: "Sanjay Yadav",
    title: "Senior Executive - Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/sanjay-yadav",
    company: "Knorr-Bremse",
    website: "http://www.knorr-bremse.com/",
    company_linkedin: "http://www.linkedin.com/company/knorr-bremse",
    location: "Pune, India",
    industry: "Automotive",
  },

  {
    id: 89,
    name: "Navya Pasupuleti",
    title: "Sr. Talent Magnet",
    linkedin: "http://www.linkedin.com/in/navya-pasupuleti-ba7a11124",
    company: "Keka HR",
    website: "http://www.keka.com/",
    company_linkedin: "http://www.linkedin.com/company/keka-hr",
    facebook: "https://facebook.com/kekadotcom/",
    twitter: "https://twitter.com/KekaDotCom",
    location: "Hyderabad, India",
    industry: "Human Resources",
  },
  {
    id: 90,
    name: "Amrita Nandy",
    title: "Manager, Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/amrita-nandy",
    company: "Loop",
    website: "http://www.loophealth.com/",
    company_linkedin: "http://www.linkedin.com/company/loop-health",
    facebook: "https://www.facebook.com/loophealthindia/",
    twitter: "https://twitter.com/loophealthHQ",
    location: "Bengaluru, India",
    industry: "Hospital & Health Care",
  },
  {
    id: 91,
    name: "Nithin Gaddam",
    title: "Talent Acquisition Manager",
    linkedin: "http://www.linkedin.com/in/nithingaddam",
    company: "Celigo",
    website: "http://www.celigo.com/",
    company_linkedin: "http://www.linkedin.com/company/celigo-inc",
    facebook: "https://facebook.com/CeligoInc",
    twitter: "https://twitter.com/celigoinc",
    location: "Hyderabad, India",
    industry: "Information Technology & Services",
  },
  {
    id: 92,
    name: "Hinesh Bheda",
    title: "Talent Acquisition Head - India",
    linkedin: "http://www.linkedin.com/in/hinesh-bheda-17018a23",
    company: "Sleek",
    website: "http://www.sleek.com/",
    company_linkedin: "http://www.linkedin.com/company/sleekcorp",
    facebook: "https://www.facebook.com/sleekcorp",
    twitter: "https://twitter.com/Sleek_corp",
    location: "Mumbai, India",
    industry: "Accounting",
  },
  {
    id: 93,
    name: "Akshay Kulkarni",
    title: "Associate Director, Talent Acquisition",
    linkedin:
      "http://www.linkedin.com/in/akshay-chidambar-kulkarni-he-him-his-55ab3821",
    company: "ANSR",
    website: "http://www.ansr.com/",
    company_linkedin: "http://www.linkedin.com/company/ansr-consulting",
    twitter: "https://twitter.com/ansrglobal",
    location: "Bengaluru, India",
    industry: "Management Consulting",
  },
  {
    id: 94,
    name: "Ishika Goel",
    title: "Senior Talent Acquisition Specialist",
    linkedin: "http://www.linkedin.com/in/ishika-goel-943708182",
    company: "Park+",
    website: "http://www.parkplus.io/",
    company_linkedin: "http://www.linkedin.com/company/parkplus",
    facebook: "https://www.facebook.com/prkpls/",
    twitter: "https://twitter.com/parkplus_io",
    location: "Delhi, India",
    industry: "Online Media",
  },
  {
    id: 95,
    name: "Jaya Lakshmi",
    title: "Lead -Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/jaya-lakshmi-23241137",
    company: "RapidAI",
    website: "http://www.rapidai.com/",
    company_linkedin: "http://www.linkedin.com/company/rapid-ai",
    facebook: "https://facebook.com/pg/rapidai/",
    twitter: "https://twitter.com/rapidai",
    location: "Bengaluru, India",
    industry: "Medical Devices",
  },
  {
    id: 96,
    name: "Ashna Thakur",
    title: "Talent Acquisition Lead",
    linkedin: "http://www.linkedin.com/in/ashna-thakur-530b1278",
    company: "Hevo Data",
    website: "http://www.hevodata.com/",
    company_linkedin: "http://www.linkedin.com/company/hevodata",
    facebook: "https://facebook.com/HevoData/",
    twitter: "https://twitter.com/HevoData",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 97,
    name: "Aishwarya R",
    title: "Senior Recruiter",
    linkedin: "http://www.linkedin.com/in/aishwaryaofficial",
    company: "Replicon",
    website: "http://www.replicon.com/",
    company_linkedin: "http://www.linkedin.com/company/replicon",
    facebook: "http://www.facebook.com/Replicon.inc",
    twitter: "http://www.twitter.com/replicon",
    location: "India",
    industry: "Information Technology & Services",
  },
  {
    id: 98,
    name: "Monisha Mendi",
    title: "Senior Talent Acquisition Specialist",
    linkedin: "http://www.linkedin.com/in/monnishaa",
    company: "Sigmoid",
    website: "http://www.sigmoid.com/",
    company_linkedin: "http://www.linkedin.com/company/sigmoid-analytics",
    facebook: "http://www.facebook.com/pages/Sigmoid-Analytics/237480799741290",
    twitter: "http://twitter.com/sigmoidInc",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 99,
    name: "Saicharan Manipatruni",
    title: "Talent Acquisition Lead",
    linkedin: "http://www.linkedin.com/in/saicharan-manipatruni-5a15434a",
    company: "DataWeave",
    website: "http://www.dataweave.com/",
    company_linkedin: "http://www.linkedin.com/company/dataweave",
    facebook: "https://www.facebook.com/DataWeave/",
    twitter: "https://twitter.com/dataweavein",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 100,
    name: "Akash Raj",
    title: "Senior Recruiter",
    linkedin: "http://www.linkedin.com/in/akash-raj-5b786694",
    company: "FloBiz",
    website: "http://www.flobiz.in/",
    company_linkedin: "http://www.linkedin.com/company/flobiz",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 101,
    name: "Neha Choudhary",
    title: "Talent Acquisition Lead",
    linkedin: "http://www.linkedin.com/in/neha-nag-choudhary-47ab4a103",
    company: "Khatabook",
    company_linkedin: "http://www.linkedin.com/company/khatabook",
    location: "Bengaluru, India",
    industry: "Financial Services",
  },
  {
    id: 102,
    name: "Asnika Das",
    title: "Manager Talent Management",
    linkedin: "http://www.linkedin.com/in/asnika-das-679b947",
    company: "ideaForge",
    website: "http://www.ideaforgetech.com/",
    company_linkedin: "http://www.linkedin.com/company/ideaforge",
    facebook: "https://www.facebook.com/ideaforge/",
    twitter: "https://twitter.com/ideaforge_tech",
    location: "Mumbai, India",
    industry: "Aviation & Aerospace",
  },
  {
    id: 103,
    name: "Aravind Subash",
    title: "Lead - Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/aravindsubash",
    company: "Increff",
    website: "http://www.increff.com/",
    company_linkedin: "http://www.linkedin.com/company/increff",
    facebook:
      "https://www.facebook.com/pages/category/Software-Company/Increff-317897195823739/",
    twitter: "https://twitter.com/increff",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 104,
    name: "Madhuri Sinha",
    title: "Talent Acquisition Lead",
    linkedin: "http://www.linkedin.com/in/madhuri-sinha-55a04b19",
    company: "Mindbowser",
    website: "http://www.mindbowser.com/",
    company_linkedin: "http://www.linkedin.com/company/mindbowser",
    facebook: "https://www.facebook.com/mindbowser/",
    twitter: "https://twitter.com/mindbowser",
    location: "Pune, India",
    industry: "Information Technology & Services",
  },
  {
    id: 105,
    name: "Neha Prakash",
    title: "Talent Acquisition Lead",
    linkedin: "http://www.linkedin.com/in/neha-prakash-883b68a1",
    company: "Zimyo",
    website: "http://www.zimyo.com/",
    company_linkedin: "http://www.linkedin.com/company/zimyo",
    facebook: "https://www.facebook.com/Zimyo-101826405031222/",
    twitter: "https://twitter.com/Zimyo",
    location: "Bengaluru, India",
    industry: "Human Resources",
  },
  {
    id: 106,
    name: "Pavan Satturu",
    title: "Talent Acquisition Lead",
    linkedin: "http://www.linkedin.com/in/pavan-satturu-202b3939",
    company: "Pyramid Consulting",
    website: "http://www.pyramidci.com/",
    company_linkedin: "http://www.linkedin.com/company/pyramid-consulting",
    facebook: "https://www.facebook.com/PyramidConsulting/",
    twitter: "https://twitter.com/pyramid_consult",
    location: "Hyderabad, India",
    industry: "Information Technology & Services",
  },
  {
    id: 107,
    name: "Nandan Goli",
    title: "Senior Talent Acquisition Specialist",
    linkedin: "http://www.linkedin.com/in/nandan-goli-7b0a2818",
    company: "Isprava",
    website: "http://www.isprava.com/",
    company_linkedin: "http://www.linkedin.com/company/isprava",
    facebook: "https://www.facebook.com/isprava/",
    twitter: "https://twitter.com/isprava",
    location: "Mumbai, India",
    industry: "Real Estate",
  },
  {
    id: 108,
    name: "Harshvardhan Vaghari",
    title: "Lead Talent Acquisition",
    linkedin: "http://www.linkedin.com/in/harshvardhan-vaghari-28b26118",
    company: "Curefoods",
    website: "http://www.curefoods.com/",
    company_linkedin: "http://www.linkedin.com/company/curefoods",
    facebook: "https://www.facebook.com/curefoods/",
    twitter: "https://twitter.com/curefoods",
    location: "Mumbai, India",
    industry: "Food & Beverages",
  },
  {
    id: 109,
    name: "Parul Jain",
    title: "Senior Talent Acquisition Partner",
    linkedin: "http://www.linkedin.com/in/parul-jain-8a041b8",
    company: "Blue Prism",
    website: "http://www.blueprism.com/",
    company_linkedin: "http://www.linkedin.com/company/blue-prism",
    facebook: "https://www.facebook.com/BluePrism/",
    twitter: "https://twitter.com/blue_prism",
    location: "Gurugram, India",
    industry: "Information Technology & Services",
  },
  {
    id: 110,
    name: "Ritika Kumari",
    title: "Talent Acquisition Manager",
    linkedin: "http://www.linkedin.com/in/ritika-kumari-9b56a8a7",
    company: "Firstsource Solutions",
    website: "http://www.firstsource.com/",
    company_linkedin: "http://www.linkedin.com/company/firstsource-solutions",
    facebook: "https://www.facebook.com/FirstsourceSolutions/",
    twitter: "https://twitter.com/firstsource",
    location: "Kolkata, India",
    industry: "Outsourcing/Offshoring",
  },

  {
    id: 111,
    name: "Saurav Patnaik",
    title: "All things in recruitment and campus placement",
    linkedin_url: "http://www.linkedin.com/in/sauravkumarpatnaik",
    company: "Yellow.ai",
    company_website: "http://www.yellow.ai/",
    company_linkedin: "http://www.linkedin.com/company/yellowdotai",
    facebook: "https://www.facebook.com/YellowMssngr",
    twitter: "https://twitter.com/yellowmssngr",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 112,
    name: "Natya Machaiah",
    title: "Talent Evangelist - Talent & Community",
    linkedin_url:
      "http://www.linkedin.com/in/natya-machaiah-hyperverge--89772712b",
    company: "HyperVerge",
    company_website: "http://www.hyperverge.co/",
    company_linkedin: "http://www.linkedin.com/company/hyperverge-inc-",
    facebook: "https://www.facebook.com/pg/HyperVerge/",
    twitter: "https://twitter.com/HyperVerge",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 113,
    name: "Sasank Pandey",
    title: "Associate Director Talent Acquisition",
    linkedin_url: "http://www.linkedin.com/in/sasank-pandey-0119b970",
    company: "Hevo Data",
    company_website: "http://www.hevodata.com/",
    company_linkedin: "http://www.linkedin.com/company/hevodata",
    facebook: "https://facebook.com/HevoData/",
    twitter: "https://twitter.com/HevoData",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 114,
    name: "Mehak Arora",
    title: "Recruitment Specialist",
    linkedin_url: "http://www.linkedin.com/in/mehak-arora-76153613b",
    company: "AlertEnterprise",
    company_website: "http://www.alertenterprise.com/",
    company_linkedin: "http://www.linkedin.com/company/alertenterprise",
    facebook: "https://www.facebook.com/AlertEnterprise.Inc/",
    twitter: "http://www.twitter.com/AlertEnterprise",
    location: "Chandigarh, India",
    industry: "Information Technology & Services",
  },
  {
    id: 115,
    name: "Mukarrum Pasha",
    title: "Associate Director of Talent Acquisition",
    linkedin_url: "http://www.linkedin.com/in/mukarrumpasha",
    company: "nference",
    company_website: "http://www.nference.com/",
    company_linkedin: "http://www.linkedin.com/company/nference",
    facebook: "https://facebook.com/nferencelabs/",
    twitter: "https://twitter.com/_nference",
    location: "Bengaluru, India",
    industry: "Research",
  },
  {
    id: 116,
    name: "Madhavi Chauhan",
    title: "Senior Manager Talent Acquisition",
    linkedin_url: "http://www.linkedin.com/in/madhavi-chauhan-ab2b863a",
    company: "Park+",
    company_website: "http://www.parkplus.io/",
    company_linkedin: "http://www.linkedin.com/company/parkplus",
    facebook: "https://www.facebook.com/prkpls/",
    twitter: "https://twitter.com/parkplus_io",
    location: "Delhi, India",
    industry: "Online Media",
  },
  {
    id: 117,
    name: "Divya Dubey",
    title: "Senior Recruitment Consultant",
    linkedin_url: "http://www.linkedin.com/in/divya-dubey-829649148",
    company: "Replicon",
    company_website: "http://www.replicon.com/",
    company_linkedin: "http://www.linkedin.com/company/replicon",
    facebook: "http://www.facebook.com/Replicon.inc",
    twitter: "http://www.twitter.com/replicon",
    location: "Mumbai, India",
    industry: "Information Technology & Services",
  },
  {
    id: 118,
    name: "Milan Singh",
    title: "Senior Talent Acquisition (Tech)",
    linkedin_url: "http://www.linkedin.com/in/milan-singh-b3a375186",
    company: "Park+",
    company_website: "http://www.parkplus.io/",
    company_linkedin: "http://www.linkedin.com/company/parkplus",
    facebook: "https://www.facebook.com/prkpls/",
    twitter: "https://twitter.com/parkplus_io",
    location: "Noida, India",
    industry: "Online Media",
  },
  {
    id: 119,
    name: "Shwetha Sharma",
    title: "Associate Manager Talent Acquisition",
    linkedin_url: "http://www.linkedin.com/in/shwetha-sharma-2b071818",
    company: "Vymo",
    company_website: "http://www.vymo.com/",
    company_linkedin: "http://www.linkedin.com/company/vymo",
    facebook: "https://www.facebook.com/Vymo-876315759143254/?fref=ts",
    twitter: "https://twitter.com/teamvymo",
    location: "Bengaluru, India",
    industry: "Information Technology & Services",
  },
  {
    id: 120,
    name: "Priyanshi Gupta",
    title: "Senior Talent Advisor",
    linkedin_url: "http://www.linkedin.com/in/priyanshi-gupta01",
    company: "Skuad",
    company_website: "http://www.skuad.io/",
    company_linkedin: "http://www.linkedin.com/company/joinskuad",
    facebook: "https://www.facebook.com/joinskuad.io/",
    twitter: "https://twitter.com/joinskuad",
    location: "Indore, India",
    industry: "Information Technology & Services",
  },
  {
    id: 121,
    name: "Tarvinder Singh",
    title: "Talent Acquisition Executive/ Generalist",
    linkedin_url: "http://www.linkedin.com/in/tarvinder-singh-4873681a4",
    company: "AGNEXT",
    company_website: "http://www.agnext.com/",
    company_linkedin: "http://www.linkedin.com/company/agnextworld",
    facebook: "https://facebook.com/agnextworld",
    twitter: "https://twitter.com/agnextworld",
    location: "Gurugram, India",
    industry: "Information Technology & Services",
  },
  {
    id: 122,
    name: "Usha Yadav",
    title: "Talent Acquisition Lead",
    linkedin_url: "http://www.linkedin.com/in/usha-yadav-a8299960",
    company: "Hive",
    company_website: "http://www.thehive.ai/",
    company_linkedin: "http://www.linkedin.com/company/hiveai",
    twitter: "https://twitter.com/hive_ai",
    location: "Noida, India",
    industry: "Information Technology & Services",
  },
  {
    id: 123,
    name: "Priyamvada Sinha",
    title: "Director Talent Acquisition",
    linkedin_url: "http://www.linkedin.com/in/priyamtalent",
    company: "Cowbell",
    company_website: "http://www.cowbell.insure/",
    company_linkedin: "http://www.linkedin.com/company/cowbell-cyber",
    facebook: "https://facebook.com/cowbellcyber/",
    twitter: "https://twitter.com/cowbellcyber",
    location: "Pune, India",
    industry: "Insurance",
  },
  {
    id: 124,
    name: "Sumit Singh",
    title: "Team Lead | Technical Recruiter | Gig-Force Hiring",
    linkedin_url: "http://www.linkedin.com/in/sumitkrsingh",
    company: "Truelancer.com",
    company_website: "http://www.truelancer.com/",
    company_linkedin: "http://www.linkedin.com/company/truelancer",
    facebook: "https://www.facebook.com/truelancerofficial",
    twitter: "http://twitter.com/@truelancer_",
    location: "New Delhi, India",
    industry: "Staffing & Recruiting",
  },
 

];
